import LocalizedStrings from 'localized-strings';

export default new LocalizedStrings({
    uz: {
        main: 'Asosiy',
        category: 'Bo\'limlar',
        history: 'Qaydnoma',
        favorite: 'Yoqtirilganlar',
        login: 'Sistemaga kirish',
        singIn: 'Kirish',
        username: 'Login',
        password: 'Parol',
        searchProduct: 'Mahsulot qidirish',
        inStock: 'Omborda',
        minimumOrder: 'Eng kami',
        manufacturer: 'Firma',
        piece: 'Dona',
        priceUnit: 'sum/dona',
        ordering: 'Buyurtma',
        price: 'Narxi',
        orderStatus: 'Buyurtma holati',
        orderAmount: 'Buyurtma soni',
        orderPrice: 'Buyurtma narxi',
        orderDate: 'Buyurtma sanasi',
        deliveryDate: 'Yetkazilgan vaqti',
        accept: 'Tasdiqlash',
        user: 'Foydalanuvchi',
        delivery: 'Yetkazib berish',
        hours: 'soat',
        payment: 'To`lov',
        paymentOnDelivery: 'Borganda tulash',
        manufacturerName: 'Firma nomi',
        showMore: 'Ko`proq ko`rsatish',
        exchange: 'Alishtirish',
        activeOrders: 'Faol buyurtmalar',
        homePage: 'Bosh sahifa',
        option: 'Tanlov',
        type: 'Tur',
        totalPrice: 'Umumiy narx',
        uzs: 'UZS',
        orderSuccessful: 'Muvaffaqiyatli yakunlandi!',
        wallet: 'Mening hisobim',
        inYourBalance: 'Hisobingizda',
        bonusBalance: 'Bonus balansi',
        fillBalance: 'Hisobingizni to\'ldiring',
        enterCardNumber: 'Karta raqamini kiriting',
        expireDate: 'Amal qilish muddati',
        sendConfirmationNumber: 'Tasdiqlash kodini yuborish',
        cash: 'Naxt',
        credit: 'Kredit kartasi',
        cancel: 'Bekor qilish',
    },
    ru: {
        main: 'Главный',
        category: 'Категория',
        history: 'История',
        favorite: 'Любимый',
        login: 'Войти в систему',
        singIn: 'Войти',
        username: 'Имя пользователя',
        password: 'Пароль',
        searchProduct: 'Поиск продукта',
        inStock: 'В запасе',
        minimumOrder: 'Минимальный заказ',
        manufacturer: 'Фирма',
        piece: 'штук',
        priceUnit: 'сум/штук',
        ordering: 'Заказать',
        price: 'Цена',
        orderStatus: 'Статус заказа',
        orderAmount: 'Количество заказа',
        orderPrice: 'Цена заказа',
        orderDate: '',
        deliveryDate: '',
        accept: 'Принимать',
        user: 'Пользователь',
        delivery: 'Доставка',
        hours: 'часов',
        payment: 'Оплата',
        paymentOnDelivery: 'Оплата при доставке',
        manufacturerName: 'Наименование производителя',
        showMore: 'Показать больше',
        exchange: 'Обмен',
        activeOrders: 'Активные заказы',
        homePage: 'Главная страница',
        option: 'Выбор',
        type: 'Тип',
        totalPrice: 'Итоговая цена',
        uzs: 'UZS',
        orderSuccessful: 'Заказ успешно!',
        wallet: 'Кошелек',
        inYourBalance: 'В вашем балансе',
        bonusBalance: 'Бонусный баланс',
        fillBalance: 'Пополнитe баланс',
        enterCardNumber: 'Введите номер карты',
        expireDate: 'Годен до',
        sendConfirmationNumber: 'Отправить номер подтверждения',
        cash: 'Наличные',
        credit: 'Кредитная карта',
        cancel: 'Отмена',
    },
    eng: {
        main: 'Main',
        category: 'Category',
        history: 'History',
        favorite: 'Favorite',
        login: 'Login',
        singIn: 'Sign in',
        username: 'username',
        password: 'Password',
        searchProduct: 'Search Product',
        inStock: 'In stock',
        minimumOrder: 'Minimum order',
        manufacturer: 'Manufacturer',
        piece: 'pieces',
        priceUnit: 'sum/piece',
        ordering: 'Order',
        price: 'Price',
        orderStatus: 'Status of Order',
        orderAmount: 'Amount of Order',
        orderPrice: 'Price of Order',
        orderDate: 'Order date',
        deliveryDate: 'Delivery date',
        accept: 'Accept',
        user: 'User',
        delivery: 'Delivery',
        hours: 'hours',
        payment: 'Payment',
        paymentOnDelivery: 'Payment on delivery',
        manufacturerName: 'Name of manufacturer',
        showMore: 'Show more',
        exchange: 'Exchange',
        activeOrders: 'Active orders',
        homePage: 'Home page',
        option: 'Option',
        type: 'Type',
        totalPrice: 'Total price',
        uzs: 'UZS',
        orderSuccessful: 'Order Successful!',
        wallet: 'Wallet',
        inYourBalance: 'In your balance',
        bonusBalance: 'Bonus balance',
        fillBalance: 'Fill the balance',
        enterCardNumber: 'Enter card number',
        expireDate: 'Expire date',
        sendConfirmationNumber: 'Send confirmation number',
        cash: 'Cash',
        credit: 'Credit card',
        cancel: 'Cancel',
    },
});
