import LocalizedStrings from 'localized-strings';

export default new LocalizedStrings({
  uz: {
    main: 'Asosiy',
    category: "Bo'imlar",
    history: 'Qaydnoma',
    favorite: 'Yoqtirilganlar',
    login: 'Sistemaga kirish',
    singIn: 'Kirish',
    username: 'Login',
    password: 'Parol',
    searchProduct: 'Mahsulot qidirish',
    inStock: 'Omborda',
    minimumOrder: 'Eng kami',
    manufacturer: 'Firma',
    piece: 'dona',
    priceUnit: 'sum/dona',
    ordering: 'Buyurtma',
  },
  ru: {
    main: 'Главный',
    category: 'Категория',
    history: 'История',
    favorite: 'Любимый',
    login: 'Войти в систему',
    singIn: 'Войти',
    username: 'Имя пользователя',
    password: 'Пароль',
    searchProduct: 'Поиск продукта',
    inStock: 'В запасе',
    minimumOrder: 'Минимальный заказ',
    manufacturer: 'Фирма',
    piece: 'штук',
    priceUnit: 'сум/штук',
    ordering: 'Заказать',
  },
  angliskiy: {
    main: 'Main',
    category: 'Category',
    history: 'History',
    favorite: 'Favorite',
    login: 'Login',
    singIn: 'Sign in',
    username: 'username',
    password: 'Password',
    searchProduct: 'Search Product',
    inStock: 'In stock',
    minimumOrder: 'Minimum order',
    manufacturer: 'Manufacturer',
    piece: 'pieces',
    priceUnit: 'sum/piece',
    ordering: 'Order',
  },
});
